---
name: govulncheck
on:
  pull_request:
    paths:
      - .github/workflows/govulncheck.yml
      - go.mod
      - go.sum
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/govulncheck.yml
      - go.mod
      - go.sum
  schedule:
    - cron: '33 2 * * *'

permissions:
  contents: read

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # v1.0.4
